### PR TITLE
Introduce install type

### LINKED ISSUE #201: Use go install for tools with dynamic linked libraries
### Please describe your feature request:
Tools such as `naabu` and `katana` are dynamically linked against c libraries (`libpcap` and `tree-sitter` respectively). When these tools are executed on systems with a different c toolset, they fail because the version might be different (`glibc`).
The preferred way of installing these tools should be via go install, as it will ensure that compiler and linker are consistent with the runtime c toolset available on the system.

Having pdtm installed in most cases implies already the presence of go on the system (it's the recommended way to install `pdtm`).

Ref: https://github.com/projectdiscovery/pdtm/issues/8#issuecomment-1362005549

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #201.

```console
$ go run . -i katana,nuclei

                ____
     ____  ____/ / /_____ ___
    / __ \/ __  / __/ __ __  \
   / /_/ / /_/ / /_/ / / / / /
  / .___/\__,_/\__/_/ /_/ /_/
 /_/

		projectdiscovery.io

[INF] Current pdtm version v0.0.8 (latest)
[INF] installing katana with go install...
[INF] installed katana 1.0.4 (latest)
[INF] installing nuclei...
[INF] installed nuclei 2.9.15 (latest)
```

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]
lgtm - It seems like api is still not deployed

**Comment by ehsandeep** [comment]
@Mzack9999 @dogancanbakir, new changes are now live - https://api.pdtm.sh/api/v1/tools/aix

**Comment by dogancanbakir** [comment]
@ehsandeep,
Thank you for deploying the changes. We can proceed with the merge now.

**Review by ehsandeep — CHANGES_REQUESTED** [review]
```console
./pdtm -i katana

                ____          
     ____  ____/ / /_____ ___ 
    / __ \/ __  / __/ __ __  \
   / /_/ / /_/ / /_/ / / / / /
  / .___/\__,_/\__/_/ /_/ /_/ 
 /_/                         

		projectdiscovery.io

[INF] Current pdtm version v0.0.8 (latest)
[INF] installing katana with go install...
[ERR] katana: go install failed 
```

we can fallback to downloading binary in case of go is not available on system.

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
